[project]
name = "conditional-vae-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["matplotlib>=3.10.1", "torch>=2.6.0"]
